# -*- coding: utf-8 -*-
"""
Quota Subgraph Cleanup Script (Safe, Schema-Aware)

This script removes all nodes and relationships belonging to the new quota ontology
WITHOUT dropping the entire Neo4j database.

What this script does:
    ✓ Deletes nodes under specific labels (sub_item_work, work_content, etc.)
    ✓ Deletes all relationships connected to those nodes (via DETACH DELETE)
    ✓ Removes ONLY constraints created by the quota-import script (names start with 'uq_')
    ✓ Works in both single-database and multi-database Neo4j setups
    ✓ Supports batched deletion to avoid transaction explosions

What this script does NOT do:
    ✗ It does NOT drop the database
    ✗ It does NOT delete unrelated parts of the knowledge graph
"""

import re
from neo4j import GraphDatabase
from neo4j.exceptions import ClientError

# -------------------------------------------------------------------
# Neo4j connection configuration
# -------------------------------------------------------------------
NEO4J_URI      = "bolt://localhost:7687"
NEO4J_USER     = "neo4j"
NEO4J_PASSWORD = "strongpassword123"
TARGET_DB      = "quota"  # target database; fallback to default if not found

# -------------------------------------------------------------------
# Labels belonging to the quota ontology (only these are removed)
# -------------------------------------------------------------------
LABELS = [
    "sub_item_work",
    "work_content",
    "specialty_subdivision",
    "specialty_subdivision_type",
    "sub_divisional_work",
    "resource_item",
]

# -------------------------------------------------------------------
# Constraint names generated by the import script (must be dropped)
# -------------------------------------------------------------------
CONSTRAINT_NAME_PREFIXES = [
    "uq_sdw_id",  # sub_divisional_work.id
    "uq_sst_id",  # specialty_subdivision_type.id
    "uq_ss_id",   # specialty_subdivision.id
    "uq_wc_id",   # work_content.id
    "uq_si_id",   # sub_item_work.id
    "uq_ri_id",   # resource_item.id
]

# Maximum batch delete size
BATCH_LIMIT = 10000


# ===================================================================
# Database helper utilities
# ===================================================================
def has_multi_db(driver) -> bool:
    """Return True if this Neo4j instance supports multi-database."""
    try:
        with driver.session(database="system") as s:
            s.run("SHOW DATABASES").consume()
        return True
    except ClientError:
        return False


def db_exists_online(driver, dbname: str) -> bool:
    """Check whether a database exists and is online."""
    try:
        with driver.session(database="system") as s:
            rec = s.run(
                "SHOW DATABASES YIELD name, currentStatus "
                "WHERE name = $n RETURN currentStatus",
                n=dbname
            ).single()
            return bool(rec and rec["currentStatus"] == "online")
    except ClientError:
        return False


def pick_database(driver, target_name: str):
    """
    Decide which database to use for the cleanup session.

    Rules:
        - If multi-database is supported AND target database exists → use it.
        - Otherwise → use the default database (return None).
    """
    if has_multi_db(driver) and db_exists_online(driver, target_name):
        print(f"[INFO] Using target database `{target_name}`")
        return target_name
    print("[INFO] Using default database (no multi-db support or target db unavailable)")
    return None


# ===================================================================
# Constraint cleanup
# ===================================================================
def drop_constraints(session):
    """
    Drop ONLY the constraints created by the quota-import script.
    These constraints all start with prefix 'uq_'.

    Uses SHOW CONSTRAINTS for newer Neo4j versions, but falls back to
    direct DROP attempts for older versions.
    """
    try:
        result = session.run("SHOW CONSTRAINTS YIELD name RETURN name")
        names = [r["name"] for r in result]

        for n in names:
            if any(n.startswith(p) for p in CONSTRAINT_NAME_PREFIXES):
                session.run(f"DROP CONSTRAINT {n} IF EXISTS").consume()

    except ClientError:
        # Older Neo4j versions (e.g., 3.x/4.x) — fallback:
        for n in CONSTRAINT_NAME_PREFIXES:
            try:
                session.run(f"DROP CONSTRAINT {n} IF EXISTS").consume()
            except ClientError:
                pass


# ===================================================================
# Node deletion
# ===================================================================
def detach_delete_by_labels(session):
    """
    Batch delete all nodes under the target labels.
    DETACH DELETE ensures all relationships are removed safely.

    Batching prevents transaction timeouts for large graphs.
    """
    for lab in LABELS:
        while True:
            rec = session.run(f"MATCH (n:`{lab}`) RETURN count(n) AS cnt").single()
            cnt = rec["cnt"] if rec else 0

            if cnt == 0:
                break

            session.run(
                f"MATCH (n:`{lab}`) WITH n LIMIT $lim DETACH DELETE n",
                lim=BATCH_LIMIT
            ).consume()

        print(f"[CLEAN] Label `{lab}` cleared.")


# ===================================================================
# Main execution
# ===================================================================
def main():
    driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))

    db_for_session = pick_database(driver, TARGET_DB)

    # ---- cleanup transaction ----
    with driver.session(database=db_for_session) as session:
        print("[STEP] Dropping import-created constraints...")
        drop_constraints(session)

        print("[STEP] Deleting nodes/relationships (batched)...")
        detach_delete_by_labels(session)

    driver.close()
    print("✅ Cleanup complete. (Database itself was not dropped.)")


if __name__ == "__main__":
    main()
